# -*- mode: python ; coding: utf-8 -*-

block_cipher = None

a = Analysis(
    ['main.py'],
    pathex=['.'],
    binaries=[],
    datas=[
        ('MaterialDatabase.py', '.'),
        ('GeometryGenerator.py', '.'),
        ('LoadManager.py', '.'),
        ('DocumentExporter.py', '.'),
        ('ProjectData.py', '.'),
        ('Node.py', '.'),
        ('C3D4.py', '.'),
        ('FEM.py', '.'),
        ('Boundary.py', '.'),
        ('Dmatrix.py', '.'),
    ],
    hiddenimports=[
        'numpy',
        'scipy',
        'scipy.linalg',
        'matplotlib',
        'matplotlib.backends.backend_tkagg',
        'mpl_toolkits.mplot3d',
        'tetgen',
        'stl',
        'tkinter',
        'tkinter.ttk',
        'tkinter.filedialog',
        'tkinter.messagebox',
        'reportlab',
        'reportlab.lib',
        'reportlab.lib.pagesizes',
        'reportlab.platypus',
        'reportlab.graphics',
        'PIL',
        'PIL.Image',
        # mypyc関連のモジュールを明示的に除外
        'mypy',
        'mypy.nodes',
        'mypy.types',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        # mypycで最適化されたモジュールを除外
        'mypy',
        'mypy.nodes',
        'mypy.types',
        'mypy.visitor',
        'mypy.traverser',
        'mypy.options',
        'mypy.errors',
        'mypy.messages',
        'mypy.version',
        # 不要な大きなパッケージを除外
        'torch',
        'torchvision',
        'tensorflow',
        'keras',
        'sklearn',
        'pandas',
        'seaborn',
        'plotly',
        'vtk',
        'mayavi',
        'cv2',
        'jupyter',
        'notebook',
        'IPython',
        # 開発ツール関連
        'pytest',
        'black',
        'flake8',
        'pylint',
        'autopep8',
        'isort',
        # ドキュメント生成ツール
        'sphinx',
        'docutils',
        'jinja2',
        # その他不要なモジュール
        'sqlalchemy',
        'psycopg2',
        'pymongo',
        'redis',
        'celery',
        'django',
        'flask',
        'fastapi',
    ],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='PythonFEMTool',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)